### ISSUE TITLE
i need  login credentials

### ISSUE THREAD

**Issue by pnagampalli** [DhvanilP/OuRCTC#1]
can i get login credentials of this project. Hope i get it as soon as possible . please do reply

**Comment by dhvanilp** [comment]
Login credentials of what?

**Comment by pnagampalli** [comment]
Bro username and password

**Comment by dhvanilp** [comment]
If u r asking for django part just create a new super user....
Google it, it was something like python manage.py createsuperuser.... I
dont remember it exactly.
I don't remember it too!

**Comment by pnagampalli** [comment]
Ohh okay fine bro
Thank you

**Comment by pnagampalli** [comment]
bro can I get ur number?

**Comment by dhvanilp** [comment]
No but, you can mail me at dhvanilhparikh@gmail.com or Shreyas at shreyas.shankar920@gmail.com.

**Comment by pnagampalli** [comment]
Actually when we login then comes a page of source and destination of train
ticket booking with date but it's like we are not getting the availability
of trains but there's an error I don't know how to do it so, can you help
out

**Comment by shrey920** [comment]
We had just made the trains available for a certain dates and not entirely. If you can access django admin page just check the trains table in the database and select those dates. As far as I remember, I had put only the days of November 2018 in the directory. If you need more dates, just create entries in the trains table. Hope I could solve your doubt.
